# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ML-testing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MLEngine-iOS', :git => 'https://github.com/tnmrajesh/TechML.git', :tag => '1.0.8'
  # Pods for ML-testing

end
