# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'
#inhibit_all_warnings!

target 'ML-sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MLEngine-iOS', :git => 'https://github.com/tnmrajesh/TechML.git', :tag => '1.0.3'
  # Pods for ML-sample
#  pod 'TensorFlowLiteSwift', :inhibit_warnings => true
end
